Repository microsoft/Microsoft365DSC, pull requests merged in 2019-11, with the labels that each got.

#227 Add Validation of CIMInstances in Test-Office365DSCParameterState
  CHANGELOG.md
  Modules/Office365DSC/DSCResources/MSFT_EXOOrganizationConfig/MSFT_EXOOrganizationConfig.psm1
  Modules/Office365DSC/DSCResources/MSFT_SCComplianceSearch/MSFT_SCComplianceSearch.psm1
  Modules/Office365DSC/DSCResources/MSFT_SCComplianceTag/MSFT_SCComplianceTag.psm1
  Modules/Office365DSC/DSCResources/MSFT_SPOSearchResultSource/MSFT_SPOSearchResultSource.psm1
  Modules/Office365DSC/Modules/O365DSCReverse.psm1
  Modules/Office365DSC/Modules/Office365DSCUtil.psm1
  Modules/Office365DSC/Office365DSC.psd1
  Tests/Integration/O365Integration.Master.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.SCComplianceTag.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.SPOSearchResultSource.Tests.ps1
  appveyor.yml
  azure-pipelines.yml
Labels: Backlog, Enhancement

#221 Update MSFT_EXOAntiPhishPolicy.psm1
  Modules/Office365DSC/DSCResources/MSFT_EXOAntiPhishPolicy/MSFT_EXOAntiPhishPolicy.psm1
  Modules/Office365DSC/DSCResources/MSFT_EXOAntiPhishRule/MSFT_EXOAntiPhishRule.psm1
  Modules/Office365DSC/DSCResources/MSFT_EXOCASMailboxPlan/MSFT_EXOCASMailboxPlan.psm1
  Modules/Office365DSC/DSCResources/MSFT_EXODkimSigningConfig/MSFT_EXODkimSigningConfig.psm1
  Modules/Office365DSC/DSCResources/MSFT_EXOHostedConnectionFilterPolicy/MSFT_EXOHostedConnectionFilterPolicy.psm1
  Modules/Office365DSC/DSCResources/MSFT_EXOHostedContentFilterPolicy/MSFT_EXOHostedContentFilterPolicy.psm1
  Modules/Office365DSC/DSCResources/MSFT_EXOHostedContentFilterRule/MSFT_EXOHostedContentFilterRule.psm1
  Modules/Office365DSC/DSCResources/MSFT_EXOHostedOutboundSpamFilterPolicy/MSFT_EXOHostedOutboundSpamFilterPolicy.psm1
  Modules/Office365DSC/DSCResources/MSFT_EXOMailTips/MSFT_EXOMailTips.psm1
  Modules/Office365DSC/DSCResources/MSFT_EXOSafeAttachmentPolicy/MSFT_EXOSafeAttachmentPolicy.psm1
  Modules/Office365DSC/DSCResources/MSFT_SPOPropertyBag/MSFT_SPOPropertyBag.psm1
  Modules/Office365DSC/DSCResources/MSFT_SPOSiteAuditSettings/MSFT_SPOSiteAuditSettings.psm1
  Modules/Office365DSC/DSCResources/MSFT_SPOTenantCdnPolicy/MSFT_SPOTenantCdnPolicy.psm1
  Modules/Office365DSC/Modules/O365DSCReverse.psm1
  Modules/Office365DSC/Modules/O365DSCReverseGUI.psm1
  Tests/Integration/O365Integration.Master.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.EXOAntiPhishPolicy.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.EXOAntiPhishRule.Tests.ps1
Labels: Bug

#237 Fixes
  CHANGELOG.md
  Modules/Office365DSC/DSCResources/MSFT_SCDLPComplianceRule/MSFT_SCDLPComplianceRule.psm1
  Modules/Office365DSC/Office365DSC.psd1
  appveyor.yml
  azure-pipelines.yml
Labels: Bug

#242 SCFilePlanPropertyReferenceId
  CHANGELOG.md
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyReferenceId/MSFT_SCFilePlanPropertyReferenceId.psm1
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyReferenceId/MSFT_SCFilePlanPropertyReferenceId.schema.mof
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyReferenceId/readme.md
  Modules/Office365DSC/Examples/Resources/SCFilePlanPropertyReferenceId/1-AddingNewFilePlanPropertyReferenceId.ps1
  Tests/Integration/O365Integration.Master.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.SCFilePlanPropertyReferenceId.Tests.ps1
  Tests/Unit/Stubs/Office365.psm1
Labels: Backlog, Enhancement

#239 SCFilePlanPropertyAuthority
  CHANGELOG.md
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyAuthority/MSFT_SCFilePlanPropertyAuthority.psm1
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyAuthority/MSFT_SCFilePlanPropertyAuthority.schema.mof
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyAuthority/readme.md
  Modules/Office365DSC/Examples/Resources/SCFilePlanPropertyAuthority/1-AddingNewFilePlanPropertyCategory.ps1
  Tests/Integration/O365Integration.Master.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.SCFilePlanPropertyAuthority.Tests.ps1
  Tests/Unit/Stubs/Office365.psm1
Labels: Backlog, Enhancement

#240 SCFilePlanPropertyCategory
  CHANGELOG.md
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyCategory/MSFT_SCFilePlanPropertyCategory.psm1
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyCategory/MSFT_SCFilePlanPropertyCategory.schema.mof
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyCategory/readme.md
  Modules/Office365DSC/Examples/Resources/SCFilePlanPropertyCategory/1-AddingNewFilePlanPropertyCategory.ps1
  Tests/Integration/O365Integration.Master.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.SCFilePlanPropertyCategory.Tests.ps1
  Tests/Unit/Stubs/Office365.psm1
Labels: Backlog, Enhancement

#238 SCFilePlanPropertyCitation
  CHANGELOG.md
  Modules/Office365DSC/DSCResources/MSFT_ODSettings/MSFT_ODSettings.psm1
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyCitation/MSFT_SCFilePlanPropertyCitation.psm1
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyCitation/MSFT_SCFilePlanPropertyCitation.schema.mof
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyCitation/readme.md
  Modules/Office365DSC/Examples/Resources/SCFilePlanPropertyCitation/1-AddingNewCitation.ps1
  Modules/Office365DSC/Modules/O365DSCReverse.psm1
  Modules/Office365DSC/Modules/O365DSCReverseGUI.psm1
  Tests/Integration/O365Integration.Master.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.SCFilePlanPropertyCitation.Tests copy.ps1
  Tests/Unit/Stubs/Office365.psm1
Labels: Backlog, Enhancement

#241 SCFilePlanPropertyDepartment
  CHANGELOG.md
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyDepartment/MSFT_SCFilePlanPropertyDepartment.psm1
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyDepartment/MSFT_SCFilePlanPropertyDepartment.schema.mof
  Modules/Office365DSC/DSCResources/MSFT_SCFilePlanPropertyDepartment/readme.md
  Modules/Office365DSC/Examples/Resources/SCFilePlanPropertyDepartment/1-AddingNewFilePlanPropertyDepartment.ps1
  Tests/Integration/O365Integration.Master.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.SCFilePlanPropertyDepartment.Tests.ps1
  Tests/Unit/Stubs/Office365.psm1
Labels: Backlog, Enhancement

#245 ReverseDSC for latest PRs
  Modules/Office365DSC/Modules/O365DSCReverse.psm1
  Modules/Office365DSC/Modules/O365DSCReverseGUI.psm1
Labels: Backlog, Enhancement

#257 Fixes
  Modules/Office365DSC/DSCResources/MSFT_EXOAcceptedDomain/MSFT_EXOAcceptedDomain.psm1
  Modules/Office365DSC/DSCResources/MSFT_SPOAccessControlSettings/MSFT_SPOAccessControlSettings.psm1
  Modules/Office365DSC/DSCResources/MSFT_SPOSiteDesign/MSFT_SPOSiteDesign.psm1
  Modules/Office365DSC/DSCResources/MSFT_SPOTenantSettings/MSFT_SPOTenantSettings.psm1
  Modules/Office365DSC/DSCResources/MSFT_TeamsTeam/MSFT_TeamsTeam.psm1
  Modules/Office365DSC/DSCResources/MSFT_TeamsTeam/MSFT_TeamsTeam.schema.mof
  Modules/Office365DSC/Modules/O365DSCReverse.psm1
  Modules/Office365DSC/Modules/O365DSCReverseGUI.psm1
  Tests/Unit/Office365DSC/Office365DSC.EXOAcceptedDomain.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.SPOAccessControlSettings.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.SPOTenantSettings.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.TeamsTeam.Tests.ps1
Labels: Bug

#259 fixes for some multiple resources related to compliance
  Modules/Office365DSC/DSCResources/MSFT_EXOAcceptedDomain/MSFT_EXOAcceptedDomain.psm1
  Modules/Office365DSC/DSCResources/MSFT_SCCaseHoldPolicy/MSFT_SCCaseHoldPolicy.psm1
  Modules/Office365DSC/DSCResources/MSFT_SCCaseHoldRule/MSFT_SCCaseHoldRule.psm1
  Modules/Office365DSC/DSCResources/MSFT_SCComplianceCase/MSFT_SCComplianceCase.psm1
  Tests/Unit/Office365DSC/Office365DSC.EXOAcceptedDomain.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.SCCaseHoldPolicy.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.SCCaseHoldRule.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.SCComplianceCase.Tests.ps1
Labels: Bug

#263 SCComplianceSearch: fixed missing case name
  Modules/Office365DSC/DSCResources/MSFT_SCComplianceSearch/MSFT_SCComplianceSearch.psm1
Labels: Bug

#260 New Resource TeamsClientConfiguration
  CHANGELOG.md
  Modules/Office365DSC/DSCResources/MSFT_TeamsClientConfiguration/MSFT_TeamsClientConfiguration.psm1
  Modules/Office365DSC/DSCResources/MSFT_TeamsClientConfiguration/MSFT_TeamsClientConfiguration.schema.mof
  Modules/Office365DSC/DSCResources/MSFT_TeamsClientConfiguration/readme.md
  Modules/Office365DSC/Examples/Resources/TeamsClientConfiguration/1-ConfigureTeamsClient.ps1
  Modules/Office365DSC/Modules/O365DSCReverse.psm1
  Modules/Office365DSC/Modules/O365DSCReverseGUI.psm1
  Modules/Office365DSC/Office365DSC.psd1
  Tests/Integration/O365Integration.Master.Tests.ps1
  Tests/Unit/Office365DSC/Office365DSC.TeamsClientConfiguration.Tests.ps1
  Tests/Unit/Stubs/Office365.psm1
  appveyor.yml
  azure-pipelines.yml
Labels: Enhancement
