Repository microsoft/Microsoft365DSC, pull requests merged in 2020-05, with the labels that each got.

#468 Introduces support for AzureAD Application Authentication
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADGroupsNamingPolicy/MSFT_AADGroupsNamingPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADGroupsNamingPolicy/MSFT_AADGroupsNamingPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADGroupsNamingPolicy/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADGroupsSettings/MSFT_AADGroupsSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADGroupsSettings/MSFT_AADGroupsSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADGroupsSettings/Readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADMSGroup/MSFT_AADMSGroup.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADMSGroup/MSFT_AADMSGroup.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADMSGroup/Readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADMSGroupLifecyclePolicy/MSFT_AADMSGroupLifecyclePolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADMSGroupLifecyclePolicy/MSFT_AADMSGroupLifecyclePolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADMSGroupLifecyclePolicy/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsChannel/MSFT_TeamsChannel.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsChannel/MSFT_TeamsChannel.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsChannel/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTeam/MSFT_TeamsTeam.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTeam/MSFT_TeamsTeam.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTeam/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUser/MSFT_TeamsUser.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUser/MSFT_TeamsUser.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUser/readme.md
  Modules/Microsoft365DSC/Modules/M365DSCReverse.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADGroupsNamingPolicy.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADGroupsSettings.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADMSGroup.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADMSGroupLifecyclePolicy.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.TeamsChannel.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.TeamsTeam.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.TeamsUser.Tests.ps1
  Tests/Unit/Stubs/Generic.psm1
Labels: Bug, Enhancement

#471 Microsoft Graph and ExchangeOnline PowerShell modules support
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  appveyor.yml
  azure-pipelines.yml
Labels: Enhancement

#583 Introduced the Test-M365DSCAgent cmdlet
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCAgent.psm1
  Modules/Microsoft365DSC/Modules/M365DSCReport.psm1
  appveyor.yml
  azure-pipelines.yml
Labels: Enhancement

#585 Improvements for Report and Improved Telemetry
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCAgent.psm1
  Modules/Microsoft365DSC/Modules/M365DSCReport.psm1
  Modules/Microsoft365DSC/Modules/M365DSCReverse.psm1
  appveyor.yml
  azure-pipelines.yml
Labels: Enhancement

#596 Fix Issue 595 - Test-Microsoft365DSCParameterState was Comparing same array of object
  CHANGELOG.md
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
Labels: Bug

#594 MSFT_TeamsVoiceRoutingPolicy: Initial creation of resource
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsVoiceRoutingPolicy/MSFT_TeamsVoiceRoutingPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsVoiceRoutingPolicy/MSFT_TeamsVoiceRoutingPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsVoiceRoutingPolicy/readme.md
  Modules/Microsoft365DSC/Examples/Resources/TeamsVoiceRoutingPolicy/1-AddNewVoiceRoutingPolicy.ps1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.TeamsVoiceRoutingPolicy.Tests.ps1
  appveyor.yml
  azure-pipelines.yml
Labels: Enhancement
