Repository microsoft/Microsoft365DSC, pull requests merged in 2022-12, with the labels that each got.

#2611 Release 1.22.1130.1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.22.1130.1

#2612 Release 1.22.1130.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_SCRetentionCompliancePolicy/MSFT_SCRetentionCompliancePolicy.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.SCRetentionCompliancePolicy.Tests.ps1
  docs/docs/home/what-is-M365DSC.md
  docs/docs/user-guide/get-started/comparing-configurations.md
  docs/docs/user-guide/get-started/deploying-configurations.md
  docs/docs/user-guide/get-started/generating-reports.md
Labels: Release, V1.22.1130.1

#2630 Release 1.22.1207.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.22.1207.1

#2667 Release 1.22.1214.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.22.1214.1

#2668 Release 1.22.1214.1
  .github/workflows/Unit Tests.yml
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAdministrativeUnit/MSFT_AADAdministrativeUnit.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADEntitlementManagementAccessPackageCatalogResource/MSFT_AADEntitlementManagementAccessPackageCatalogResource.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADGroup/MSFT_AADGroup.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADUser/MSFT_AADUser.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADUser/MSFT_AADUser.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_PlannerBucket/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_PlannerPlan/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_SCRetentionComplianceRule/MSFT_SCRetentionComplianceRule.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOSite/MSFT_SPOSite.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantCdnEnabled/MSFT_SPOTenantCdnEnabled.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOUserProfileProperty/MSFT_SPOUserProfileProperty.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsChannel/MSFT_TeamsChannel.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUpdateManagementPolicy/MSFT_TeamsUpdateManagementPolicy.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCReport.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADGroup.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.TeamsUpdateManagementPolicy.Tests.ps1
  docs/docs/resources/azure-ad/AADUser.md
Labels: Release, V1.22.1214.1

#2342 IntuneDeviceConfigurationAndroidDeviceOwner: Fixes #2272 and other issues
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceOwner/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceOwner.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceOwner/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceOwner.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceOwner/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceOwner/setting.json
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneDeviceConfigurationPolicyAndroidDeviceOwner.Tests.ps1
Labels: Breaking Changes

#2705 Release 1.22.1221.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.22.1221.1
