Repository microsoft/Microsoft365DSC, pull requests merged in 2022-08, with the labels that each got.

#2161 Issue 2158
  Modules/Microsoft365DSC/Modules/M365DSCReport.psm1
Labels: Pending Information

#2220 Release 1.22.824.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release

#2174 Aad role settings
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleSetting/MSFT_AADRoleSetting.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleSetting/MSFT_AADRoleSetting.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleSetting/Readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleSetting/settings.json
  Modules/Microsoft365DSC/Examples/Resources/AADRoleSetting/1-ConfigureAADConditionalAccessPolicy.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADRoleSetting.Tests.ps1
Labels: Azure Active Directory

#2213 Avoid using Get-MgDirectoryObject cmdlet
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1
Labels: Pending Information
