Repository microsoft/Microsoft365DSC, pull requests merged in 2023-10, with the labels that each got.

#3692 PR - AADEntitlementManagementAccessPackageAssignmentPolicy - FIXES [#3639]
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADEntitlementManagementAccessPackageAssignmentPolicy/MSFT_AADEntitlementManagementAccessPackageAssignmentPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADEntitlementManagementAccessPackageAssignmentPolicy/MSFT_AADEntitlementManagementAccessPackageAssignmentPolicy.schema.mof
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADEntitlementManagementAccessPackageAssignmentPolicy.Tests.ps1
Labels: Azure Active Directory, Breaking Changes

#3778 Release 1.23.1011.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.1011.1

#3808 Release 1.23.1018.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.1018.1

#3833 Release 1.23.1025.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.1025.1
