Repository microsoft/Microsoft365DSC, pull requests merged in 2023-06, with the labels that each got.

#3386 Release 1.23.614.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.614.1

#3387 Release 1.23.614.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADNamedLocationPolicy/MSFT_AADNamedLocationPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADNamedLocationPolicy/MSFT_AADNamedLocationPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_SCProtectionAlert/MSFT_SCProtectionAlert.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsAppPermissionPolicy/MSFT_TeamsAppPermissionPolicy.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCPermissions.psm1
  docs/docs/resources/azure-ad/AADNamedLocationPolicy.md
  docs/docs/user-guide/cmdlets/Update-M365DSCAzureAdApplication.md
  docs/docs/user-guide/get-started/powershell7-support.md
Labels: Release, V1.23.614.1

#3411 Release 1.23.621.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAdministrativeUnit/MSFT_AADAdministrativeUnit.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_EXORoleGroup/MSFT_EXORoleGroup.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_O365OrgSettings/MSFT_O365OrgSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_O365OrgSettings/MSFT_O365OrgSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_O365OrgSettings/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_PPTenantIsolationSettings/MSFT_PPTenantIsolationSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_PPTenantSettings/MSFT_PPTenantSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCLabelPolicy/MSFT_SCLabelPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCProtectionAlert/MSFT_SCProtectionAlert.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Examples/Resources/O365OrgSettings/1-ConfigureOrgSettings.ps1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCPermissions.psm1
  Modules/Microsoft365DSC/Modules/M365DSCReport.psm1
  Modules/Microsoft365DSC/Modules/M365DSCStubsUtility.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  Tests/QA/Microsoft365DSC.SettingsJson.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.O365OrgSettings.Tests.ps1
  Tests/Unit/Stubs/Generic.psm1
  Tests/Unit/Stubs/Microsoft365.psm1
  docs/docs/resources/azure-ad/AADConditionalAccessPolicy.md
  docs/docs/resources/office365/O365OrgSettings.md
Labels: Release, V1.23.621.1

#3412 O365OrgSettings Updates - Forms, DCV, A&S and To Do
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_O365OrgSettings/MSFT_O365OrgSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_O365OrgSettings/MSFT_O365OrgSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_O365OrgSettings/settings.json
  Tests/Unit/Stubs/Microsoft365.psm1
Labels: On-Hold

#3430 Release 1.23.628.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.628.1
