Repository microsoft/Microsoft365DSC, pull requests merged in 2023-03, with the labels that each got.

#2953 Release v1.23.301.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.301.1

#2986 Release 1.23.308.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.308.1

#2987 Release 1.23.308.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAdministrativeUnit/MSFT_AADAdministrativeUnit.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAdministrativeUnit/MSFT_AADAdministrativeUnit.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOManagementRoleAssignment/MSFT_EXOManagementRoleAssignment.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_O365AdminAuditLogConfig/MSFT_O365AdminAuditLogConfig.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_O365AdminAuditLogConfig/MSFT_O365AdminAuditLogConfig.schema.mof
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceEnrollmentConfigurationWindows10/1-New Device Enrollment Configuration Windows 10.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsAudioConferencingPolicy/1-TeamsAudioConferencingPolicy-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsCallHoldPolicy/1-TeamsCallHoldPolicy-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsCallParkPolicy/1-TeamsCallParkPolicy-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsComplianceRecordingPolicy/1-TeamsComplianceRecordingPolicy-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsCortanaPolicy/1-TeamsCortanaPolicy-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsEnhancedEncryptionPolicy/1-TeamsEnhancedEncryptionPolicy-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsFeedbackPolicy/1-TeamsFeedbackPolicy-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsFilesPolicy/1-TeamsFilesPolicy-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsIPPhonePolicy/1-TeamsIPPhonePolicy-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsMobilityPolicy/1-TeamsMobilityPolicy-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsNetworkRoamingPolicy/1-TeamsNetworkRoamingPolicy-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsShiftsPolicy/1-TeamsShiftsPolicy-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsTenantNetworkRegion/1-TeamsTenantNetworkRegion-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsTenantNetworkSite/1-TeamsTenantNetworkSite-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsTenantNetworkSubnet/1-TeamsTenantNetworkSubnet-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsTenantTrustedIPAddress/1-TeamsTenantTrustedIPAddress-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsTranslationRule/1-TeamsTranslationRule-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsUnassignedNumberTreatment/1-TeamsUnassignedNumberTreatment-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsVdiPolicy/1-TeamsVdiPolicy-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsWorkloadPolicy/1-TeamsWorkloadPolicy-Example.ps1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCReport.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  ResourceGenerator/Module.Template.psm1
  Tests/QA/Microsoft365DSC.SettingsJson.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADAdministrativeUnit.Tests.ps1
  docs/docs/resources/azure-ad/AADAdministrativeUnit.md
  docs/docs/resources/intune/IntuneDeviceEnrollmentConfigurationWindows10.md
  docs/docs/resources/office365/O365AdminAuditLogConfig.md
  docs/docs/resources/teams/TeamsAudioConferencingPolicy.md
  docs/docs/resources/teams/TeamsCallHoldPolicy.md
  docs/docs/resources/teams/TeamsCallParkPolicy.md
  docs/docs/resources/teams/TeamsComplianceRecordingPolicy.md
  docs/docs/resources/teams/TeamsCortanaPolicy.md
  docs/docs/resources/teams/TeamsEnhancedEncryptionPolicy.md
  docs/docs/resources/teams/TeamsFeedbackPolicy.md
  docs/docs/resources/teams/TeamsFilesPolicy.md
  docs/docs/resources/teams/TeamsIPPhonePolicy.md
  docs/docs/resources/teams/TeamsMobilityPolicy.md
  docs/docs/resources/teams/TeamsNetworkRoamingPolicy.md
  docs/docs/resources/teams/TeamsShiftsPolicy.md
  docs/docs/resources/teams/TeamsTenantNetworkRegion.md
  docs/docs/resources/teams/TeamsTenantNetworkSite.md
  docs/docs/resources/teams/TeamsTenantNetworkSubnet.md
  docs/docs/resources/teams/TeamsTenantTrustedIPAddress.md
  docs/docs/resources/teams/TeamsTranslationRule.md
  docs/docs/resources/teams/TeamsUnassignedNumberTreatment.md
  docs/docs/resources/teams/TeamsVdiPolicy.md
  docs/docs/resources/teams/TeamsWorkloadPolicy.md
  docs/docs/user-guide/cmdlets/Assert-M365DSCBlueprint.md
  docs/docs/user-guide/cmdlets/Import-M365DSCDependencies.md
Labels: Release, V1.23.308.1

#3014 Release 1.23.315.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.315.1

#3017 Release 1.23.315.2
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXORoleGroup/MSFT_EXORoleGroup.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release

#3018 Release 1.23.315.2
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXORoleGroup/MSFT_EXORoleGroup.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.315.2

#3040 [BREAKING CHANGE] Removing deprecated parameters
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/MSFT_AADConditionalAccessPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/MSFT_AADConditionalAccessPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADUser/MSFT_AADUser.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADUser/MSFT_AADUser.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOAntiPhishPolicy/MSFT_EXOAntiPhishPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOAntiPhishPolicy/MSFT_EXOAntiPhishPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOHostedContentFilterPolicy/MSFT_EXOHostedContentFilterPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOHostedContentFilterPolicy/MSFT_EXOHostedContentFilterPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMalwareFilterPolicy/MSFT_EXOMalwareFilterPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMalwareFilterPolicy/MSFT_EXOMalwareFilterPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOOrganizationConfig/MSFT_EXOOrganizationConfig.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOOrganizationConfig/MSFT_EXOOrganizationConfig.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOSafeLinksPolicy/MSFT_EXOSafeLinksPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOSafeLinksPolicy/MSFT_EXOSafeLinksPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOSharedMailbox/MSFT_EXOSharedMailbox.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOSharedMailbox/MSFT_EXOSharedMailbox.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOTransportRule/MSFT_EXOTransportRule.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOTransportRule/MSFT_EXOTransportRule.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantSettings/MSFT_SPOTenantSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantSettings/MSFT_SPOTenantSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsMeetingPolicy/MSFT_TeamsMeetingPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsMeetingPolicy/MSFT_TeamsMeetingPolicy.schema.mof
  Modules/Microsoft365DSC/Examples/Resources/AADConditionalAccessPolicy/1-ConfigureAADConditionalAccessPolicy.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXOSafeLinksPolicy/1-ConfigureSafeLinksPolicy.ps1
  Modules/Microsoft365DSC/Examples/Resources/SCSensitivityLabel/1-AddingNewSensitivityLabel.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADConditionalAccessPolicy.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOHostedContentFilterPolicy.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOMalwareFilterPolicy.Tests.ps1
Labels: Breaking Changes

#3003 PR: IntuneAttackSurfaceReductionRulesPolicyWindows10ConfigManager - Fix broken resource
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneAttackSurfaceReductionRulesPolicyWindows10ConfigManager/MSFT_IntuneAttackSurfaceReductionRulesPolicyWindows10ConfigManager.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneAttackSurfaceReductionRulesPolicyWindows10ConfigManager/MSFT_IntuneAttackSurfaceReductionRulesPolicyWindows10ConfigManager.schema.mof
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneAttackSurfaceReductionRulesPolicyWindows10ConfigManager.Tests.ps1
Labels: Intune, Breaking Changes

#3077 FIXES #3072
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADGroup/MSFT_AADGroup.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADGroup/MSFT_AADGroup.schema.mof
  Modules/Microsoft365DSC/Examples/Resources/AADGroup/3-ConfigureAADGroups.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADGroup.Tests.ps1
Labels: Breaking Changes

#3106 [BREAKING CHANGE] Fixed #3024 and #3075
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseDeviceOwner/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseDeviceOwner.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseDeviceOwner/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseDeviceOwner.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseDeviceOwner/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseDeviceOwner/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseWorkProfile/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseWorkProfile.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseWorkProfile/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseWorkProfile.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseWorkProfile/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseWorkProfile/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEntrepriseDeviceOwner/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEntrepriseDeviceOwner/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEntrepriseWorkProfile/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEntrepriseWorkProfile/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowUpdateForBusinessRingUpdateProfileWindows10/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowUpdateForBusinessRingUpdateProfileWindows10/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsUpdateForBusinessRingUpdateProfileWindows10/MSFT_IntuneWindowsUpdateForBusinessRingUpdateProfileWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsUpdateForBusinessRingUpdateProfileWindows10/MSFT_IntuneWindowsUpdateForBusinessRingUpdateProfileWindows10.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsUpdateForBusinessRingUpdateProfileWindows10/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsUpdateForBusinessRingUpdateProfileWindows10/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_SCAuditConfigurationPolicy/MSFT_SCAuditConfigurationPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCAutoSensitivityLabelPolicy/MSFT_SCAutoSensitivityLabelPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCAutoSensitivityLabelRule/MSFT_SCAutoSensitivityLabelRule.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCCaseHoldPolicy/MSFT_SCCaseHoldPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCCaseHoldRule/MSFT_SCCaseHoldRule.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCComplianceCase/MSFT_SCComplianceCase.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCComplianceSearch/MSFT_SCComplianceSearch.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCComplianceSearchAction/MSFT_SCComplianceSearchAction.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCComplianceTag/MSFT_SCComplianceTag.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCDLPComplianceRule/MSFT_SCDLPComplianceRule.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCDeviceConditionalAccessPolicy/MSFT_SCDeviceConditionalAccessPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCDeviceConfigurationPolicy/MSFT_SCDeviceConfigurationPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCFilePlanPropertyAuthority/MSFT_SCFilePlanPropertyAuthority.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCFilePlanPropertyCategory/MSFT_SCFilePlanPropertyCategory.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCFilePlanPropertyCitation/MSFT_SCFilePlanPropertyCitation.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCFilePlanPropertyDepartment/MSFT_SCFilePlanPropertyDepartment.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCFilePlanPropertyReferenceId/MSFT_SCFilePlanPropertyReferenceId.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCFilePlanPropertySubCategory/MSFT_SCFilePlanPropertySubCategory.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCProtectionAlert/MSFT_SCProtectionAlert.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCRetentionEventType/MSFT_SCRetentionEventType.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCSupervisoryReviewPolicy/MSFT_SCSupervisoryReviewPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCSupervisoryReviewRule/MSFT_SCSupervisoryReviewRule.psm1
  Modules/Microsoft365DSC/Examples/Resources/IntuneWifiConfigurationPolicyAndroidEnterpriseDeviceOwner/1-ConfigureIntuneWifiConfigurationPolicyAndroidEnterpriseDeviceOwner.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneWifiConfigurationPolicyAndroidEnterpriseWorkProfile/1-ConfigureIntuneWifiConfigurationPolicyAndroidEnterpriseWorkProfile.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneWindowsUpdateForBusinessRingUpdateProfileWindows10/1-IntuneWindowsUpdateForBusinessRingUpdateProfileWindows10-Example.ps1
  ResourceGenerator/Workloads.Manifest.psd1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneWifiConfigurationPolicyAndroidEnterpriseDeviceOwner.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneWifiConfigurationPolicyAndroidEnterpriseWorkProfile.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneWindowsUpdateForBusinessRingUpdateProfileWindows10.Tests.ps1
  docs/docs/resources/intune/IntuneWifiConfigurationPolicyAndroidEnterpriseDeviceOwner.md
  docs/docs/resources/intune/IntuneWifiConfigurationPolicyAndroidEnterpriseWorkProfile.md
  docs/docs/resources/intune/IntuneWindowsUpdateForBusinessRingUpdateProfileWindows10.md
Labels: Breaking Changes
