Repository microsoft/Microsoft365DSC, pull requests merged in 2023-02, with the labels that each got.

#2865 Release 1.23.201.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_PPPowerAppsEnvironment/MSFT_PPPowerAppsEnvironment.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_PPPowerAppsEnvironment/MSFT_PPPowerAppsEnvironment.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_PlannerTask/MSFT_PlannerTask.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCComplianceCase/MSFT_SCComplianceCase.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCComplianceSearchAction/MSFT_SCComplianceSearchAction.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCProtectionAlert/MSFT_SCProtectionAlert.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCProtectionAlert/MSFT_SCProtectionAlert.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkRegion/MSFT_TeamsTenantNetworkRegion.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkRegion/MSFT_TeamsTenantNetworkRegion.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkRegion/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkRegion/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkSite/MSFT_TeamsTenantNetworkSite.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkSite/MSFT_TeamsTenantNetworkSite.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkSite/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkSite/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkSubnet/MSFT_TeamsTenantNetworkSubnet.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkSubnet/MSFT_TeamsTenantNetworkSubnet.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkSubnet/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkSubnet/settings.json
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Examples/Resources/IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled/1-IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled-Example.psm1
  Modules/Microsoft365DSC/Examples/Resources/TeamsTenantNetworkRegion/1-TeamsTenantNetworkRegion-Example.psm1
  Modules/Microsoft365DSC/Examples/Resources/TeamsTenantNetworkSite/1-TeamsTenantNetworkSite-Example.psm1
  Modules/Microsoft365DSC/Examples/Resources/TeamsTenantNetworkSubnet/1-TeamsTenantNetworkSubnet-Example.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  ResourceGenerator/M365DSCResourceGenerator.psm1
  ResourceGenerator/Module.Template.psm1
  ResourceGenerator/Schema.Template.mof
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.TeamsTenantNetworkRegion.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.TeamsTenantNetworkSite.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.TeamsTenantNetworkSubnet.Tests.ps1
  Tests/Unit/Stubs/Microsoft365.psm1
  docs/docs/resources/intune/IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled.md
  docs/docs/resources/power-platform/PPPowerAppsEnvironment.md
  docs/docs/resources/security-compliance/SCProtectionAlert.md
  docs/docs/resources/teams/TeamsTenantNetworkRegion.md
  docs/docs/resources/teams/TeamsTenantNetworkSite.md
  docs/docs/resources/teams/TeamsTenantNetworkSubnet.md
Labels: Release, V1.23.201.1

#2874 Fixed #2866, #2889 and #2890
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAdministrativeUnit/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthorizationPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_AADEntitlementManagementAccessPackage/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_AADEntitlementManagementAccessPackageCatalog/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_AADEntitlementManagementAccessPackageCatalogResource/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_AADGroup/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleSetting/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_AADSecurityDefaults/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_AADUser/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOIRMConfiguration/MSFT_EXOIRMConfiguration.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneRoleAssignment/MSFT_IntuneRoleAssignment.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_PlannerBucket/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_PlannerPlan/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_PlannerTask/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsAudioConferencingPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsCallHoldPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsCallParkPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsChannelTab/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsComplianceRecordingPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsCortanaPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsEnhancedEncryptionPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsFeedbackPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsFilesPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsIPPhonePolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsMobilityPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsNetworkRoamingPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsShiftsPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkRegion/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkSite/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTenantNetworkSubnet/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTranslationRule/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUnassignedNumberTreatment/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsVdiPolicy/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsWorkloadPolicy/settings.json
  Modules/Microsoft365DSC/Dependencies/GraphCmdletPermissions.csv
  Modules/Microsoft365DSC/Modules/M365DSCPermissions.psm1
Labels: On-Hold

#2906 Release 1.23.215.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.215.1

#2927 Release 1.23.222.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.222.1
