Repository microsoft/Microsoft365DSC, pull requests merged in 2023-01, with the labels that each got.

#2745 Release 1.23.104.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.104.1

#2746 Release 1.23.104.1
  .github/workflows/PublishGitHubPages.yml
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXODistributionGroup/MSFT_EXODistributionGroup.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOManagementRoleAssignment/MSFT_EXOManagementRoleAssignment.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneASRRulesPolicyWindows10/MSFT_IntuneASRRulesPolicyWindows10.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyMacOS/MSFT_IntuneDeviceConfigurationPolicyMacOS.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyMacOS/MSFT_IntuneDeviceConfigurationPolicyMacOS.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows10/MSFT_IntuneDeviceConfigurationPolicyWindows10.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_SCRetentionCompliancePolicy/MSFT_SCRetentionCompliancePolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCRetentionComplianceRule/MSFT_SCRetentionComplianceRule.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsEmergencyCallRoutingPolicy/MSFT_TeamsEmergencyCallRoutingPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsEmergencyCallingPolicy/MSFT_TeamsEmergencyCallingPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsFilesPolicy/MSFT_TeamsFilesPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsFilesPolicy/MSFT_TeamsFilesPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsIPPhonePolicy/MSFT_TeamsIPPhonePolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsIPPhonePolicy/MSFT_TeamsIPPhonePolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsMeetingPolicy/MSFT_TeamsMeetingPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsMeetingPolicy/MSFT_TeamsMeetingPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsShiftsPolicy/MSFT_TeamsShiftsPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsShiftsPolicy/MSFT_TeamsShiftsPolicy.schema.mof
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCReport.psm1
  ResourceGenerator/M365DSCResourceGenerator.psm1
  ResourceGenerator/Module.Template.psm1
  ResourceGenerator/Schema.Template.mof
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXODistributionGroup.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.TeamsFilesPolicy.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.TeamsIPPhonePolicy.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.TeamsShiftsPolicy.Tests.ps1
  docs/docs/resources/intune/IntuneASRRulesPolicyWindows10.md
  docs/docs/resources/intune/IntuneDeviceConfigurationPolicyMacOS.md
  docs/docs/resources/intune/IntuneDeviceConfigurationPolicyWindows10.md
  docs/docs/resources/teams/TeamsFilesPolicy.md
  docs/docs/resources/teams/TeamsIPPhonePolicy.md
  docs/docs/resources/teams/TeamsMeetingPolicy.md
  docs/docs/resources/teams/TeamsShiftsPolicy.md
Labels: Release, V1.23.104.1

#2765 Release 1.23.111.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.111.1

#2800 Release 1.23.118.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.118.1

#2838 PR: IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled - Initial release
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled/settings.json
  Modules/Microsoft365DSC/Examples/Resources/IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled/1-IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled-Example.psm1
  ResourceGenerator/M365DSCResourceGenerator.psm1
  ResourceGenerator/Module.Template.psm1
  ResourceGenerator/Schema.Template.mof
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneWindowsInformationProtectionPolicyWindows10MdmEnrolled.Tests.ps1
  Tests/Unit/Stubs/Microsoft365.psm1
Labels: On-Hold
