Repository microsoft/Microsoft365DSC, pull requests merged in 2023-04, with the labels that each got.

#3116 PR : [BREAKING CHANGE] Fixes 2933
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentStatusPageWindows10/MSFT_IntuneDeviceEnrollmentStatusPageWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentStatusPageWindows10/MSFT_IntuneDeviceEnrollmentStatusPageWindows10.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentStatusPageWindows10/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentStatusPageWindows10/settings.json
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceEnrollmentConfigurationWindows10/1-New Device Enrollment Configuration Windows 10.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceEnrollmentStatusPageWindows10/1-New Device Enrollment Status Page Windows 10.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneDeviceEnrollmentStatusPageWindows10.Tests.ps1
Labels: Breaking Changes

#3118 PR: [BREAKING CHANGE] IntuneDeviceConfigurationPolicyWindows10 - resource rework
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows10/MSFT_IntuneDeviceConfigurationPolicyWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows10/MSFT_IntuneDeviceConfigurationPolicyWindows10.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows10/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyWindows10/settings.json
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceConfigurationPolicyWindows10/1-IntuneDeviceConfigurationPolicyWindows10-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceConfigurationPolicyWindows10/1-NewIntuneDeviceConfigurationPolicyWindows10.ps1
  ResourceGenerator/M365DSCResourceGenerator.psm1
  ResourceGenerator/Module.Template.psm1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneDeviceConfigurationPolicyWindows10.Tests.ps1
Labels: Breaking Changes

#2431 PR: Breaking Change - IntuneDeviceEntollmentPlatformRestriction
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentPlatformRestriction/MSFT_IntuneDeviceEnrollmentPlatformRestriction.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentPlatformRestriction/MSFT_IntuneDeviceEnrollmentPlatformRestriction.schema.mof
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceEnrollmentPlatformRestriction/1-NewPlatformRestriction.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneDeviceEnrollmentPlatformRestriction.Tests.ps1
Labels: Breaking Changes

#3140 Release 1.23.405.1
  .vscode/settings.json
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.405.1

#3161 Release 1.23.412.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.412.1

#3192 Release 1.23.419.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOManagementRoleAssignment/MSFT_EXOManagementRoleAssignment.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationDefenderForEndpointOnboardingPolicyWindows10/MSFT_IntuneDeviceConfigurationDefenderForEndpointOnboardingPolicyWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationDefenderForEndpointOnboardingPolicyWindows10/MSFT_IntuneDeviceConfigurationDefenderForEndpointOnboardingPolicyWindows10.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationDefenderForEndpointOnboardingPolicyWindows10/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationDefenderForEndpointOnboardingPolicyWindows10/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationEmailProfilePolicyWindows10/MSFT_IntuneDeviceConfigurationEmailProfilePolicyWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationEmailProfilePolicyWindows10/MSFT_IntuneDeviceConfigurationEmailProfilePolicyWindows10.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationEmailProfilePolicyWindows10/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationEmailProfilePolicyWindows10/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationKioskPolicyWindows10/MSFT_IntuneDeviceConfigurationKioskPolicyWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationKioskPolicyWindows10/MSFT_IntuneDeviceConfigurationKioskPolicyWindows10.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationKioskPolicyWindows10/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationKioskPolicyWindows10/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_SCLabelPolicy/MSFT_SCLabelPolicy.psm1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceConfigurationDefenderForEndpointOnboardingPolicyWindows10/1-IntuneDeviceConfigurationDefenderForEndpointOnboardingPolicyWindows10-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceConfigurationEmailProfilePolicyWindows10/1-IntuneDeviceConfigurationEmailProfilePolicyWindows10-Example.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceConfigurationKioskPolicyWindows10/1-IntuneDeviceConfigurationKioskPolicyWindows10-Example.ps1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/EncodingHelpers/M365DSCStringEncoding.psm1
  Modules/Microsoft365DSC/Modules/M365DSCReport.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  ResourceGenerator/M365DSCResourceGenerator.psm1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneDeviceConfigurationDefenderForEndpointOnboardingPolicyWindows10.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneDeviceConfigurationEmailProfilePolicyWindows10.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneDeviceConfigurationKioskPolicyWindows10.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.SCLabelPolicy.Tests.ps1
  docs/docs/resources/intune/IntuneDeviceConfigurationDefenderForEndpointOnboardingPolicyWindows10.md
  docs/docs/resources/intune/IntuneDeviceConfigurationEditionUpgradePolicyWindows10.md
  docs/docs/resources/intune/IntuneDeviceConfigurationEmailProfilePolicyWindows10.md
  docs/docs/resources/intune/IntuneDeviceConfigurationKioskPolicyWindows10.md
  docs/docs/user-guide/get-started/prerequisites.md
Labels: Release, V1.23.419.1

#3229 Release 1.23.426.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.23.426.1

#3230 Release 1.23.426.1
  .github/workflows/CodeCoverage.yml
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAdministrativeUnit/MSFT_AADAdministrativeUnit.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAdministrativeUnit/MSFT_AADAdministrativeUnit.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/MSFT_AADConditionalAccessPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_O365OrgSettings/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_SCLabelPolicy/MSFT_SCLabelPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTeam/MSFT_TeamsTeam.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCReport.psm1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADAdministrativeUnit.Tests.ps1
  docs/docs/Images/Promo.png
  docs/docs/resources/azure-ad/AADAdministrativeUnit.md
  docs/docs/resources/office365/O365OrgSettings.md
  docs/docs/resources/security-compliance/SCSensitivityLabel.md
  docs/docs/user-guide/cmdlets/Compare-M365DSCConfigurations.md
Labels: Release, V1.23.426.1

#3236 Release 1.23.426.3
  CHANGELOG.md
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCReverse.psm1
Labels: V1.23.426.3
