Repository microsoft/Microsoft365DSC, pull requests merged in 2024-01, with the labels that each got.

#4043 PR: Fixes 4029
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/MSFT_AADConditionalAccessPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneSettingCatalogCustomPolicyWindows10/MSFT_IntuneSettingCatalogCustomPolicyWindows10.psm1
Labels: Pending Information

#4113 Release 1.24.103.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_M365DSCRuleEvaluation/MSFT_M365DSCRuleEvaluation.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_M365DSCRuleEvaluation/readme.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, v1.24.103.1

#3953 Fix/#3885 aad conditional access policy
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/MSFT_AADConditionalAccessPolicy.psm1
Labels: Entra ID

#4139 Release 1.24.110.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Examples/Resources/AADAuthenticationMethodPolicyAuthenticator/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/AADAuthenticationMethodPolicyAuthenticator/2-Update.ps1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.110.1

#4176 Release 1.24.117.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/MSFT_AADConditionalAccessPolicy.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.117.1

#4252 Release 1.24.124.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.124.1
