Repository microsoft/Microsoft365DSC, pull requests merged in 2024-03, with the labels that each got.

#4447 Release 1.24.313.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyAuthenticator/MSFT_AADAuthenticationMethodPolicyAuthenticator.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationStrengthPolicy/MSFT_AADAuthenticationStrengthPolicy.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.313.1

#4450 DSCParser v2
  CHANGELOG.md
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Modules/M365DSCReport.psm1
Labels: Core Engine

#4420 TeamsGroupPolicyAssignment: Skip assignments that have orphaned/deleted groups or without display name
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsGroupPolicyAssignment/MSFT_TeamsGroupPolicyAssignment.psm1
Labels: On-Hold, Pending Information

#4408 TeamsTeam: Skip teams without displayname during export
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTeam/MSFT_TeamsTeam.psm1
Labels: On-Hold, Pending Information

#4149 EXOTransportRule: Change data type of Priority from String to Int
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOTransportRule/MSFT_EXOTransportRule.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOTransportRule/MSFT_EXOTransportRule.schema.mof
Labels: Breaking Changes

#4477 Fixes #4117
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailTips/MSFT_EXOMailTips.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailTips/MSFT_EXOMailTips.schema.mof
  Modules/Microsoft365DSC/Examples/Resources/EXOMailTips/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXOMailTips/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXOMailTips/3-Remove.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOMailTips.Tests.ps1
Labels: Exchange Online, Breaking Changes

#4499 [SPOTenantSettings/SPOAccessControlSettings] Fix settings present in both resources (BREAKING CHANGE)
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOAccessControlSettings/MSFT_SPOAccessControlSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOAccessControlSettings/MSFT_SPOAccessControlSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantSettings/MSFT_SPOTenantSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantSettings/MSFT_SPOTenantSettings.schema.mof
  Modules/Microsoft365DSC/Examples/Resources/SPOAccessControlSettings/1-ConfigureSPOAccessControlSettings.ps1
  Modules/Microsoft365DSC/Examples/Resources/SPOTenantSettings/1-ConfigureSPOTenantSettings.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.SPOAccessControlSettings.Tests.ps1
Labels: SharePoint Online, Breaking Changes

#4501 FIXES #4496
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUpdateManagementPolicy/MSFT_TeamsUpdateManagementPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUpdateManagementPolicy/MSFT_TeamsUpdateManagementPolicy.schema.mof
Labels: Backlog, Teams
