Repository microsoft/Microsoft365DSC, pull requests merged in 2024-10, with the labels that each got.

#4823 EXOMailTips: Remove property Ensure
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailTips/MSFT_EXOMailTips.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailTips/MSFT_EXOMailTips.schema.mof
  Modules/Microsoft365DSC/Examples/Resources/EXOMailTips/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXOMailTips/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXOMailTips/3-Remove.ps1
  Tests/QA/Graph.PermissionList.txt
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOMailTips.Tests.ps1
Labels: Breaking Changes

#5132 Release 1.24.1002.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_ADOOrganizationOwner/MSFT_ADOOrganizationOwner.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_ADOPermissionGroup/MSFT_ADOPermissionGroup.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_DefenderSubscriptionPlan/MSFT_DefenderSubscriptionPlan.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailboxFolderPermission/MSFT_EXOMailboxFolderPermission.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCDLPComplianceRule/MSFT_SCDLPComplianceRule.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsM365App/MSFT_TeamsM365App.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  docs/docs/blog/index.md
  docs/docs/blog/october-2024-major-release.md
Labels: Breaking Changes, Release, V1.24.1002.1

#5146 AADDeviceRegistrationPolicy - Initial Release
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADDeviceRegistrationPolicy/MSFT_AADDeviceRegistrationPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADDeviceRegistrationPolicy/MSFT_AADDeviceRegistrationPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADDeviceRegistrationPolicy/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADDeviceRegistrationPolicy/settings.json
  Modules/Microsoft365DSC/Examples/Resources/AADDeviceRegistrationPolicy/2-Update.ps1
  Tests/QA/Graph.PermissionList.txt
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADDeviceRegistrationPolicy.Tests.ps1
  Tests/Unit/Stubs/Microsoft365.psm1
Labels: Entra ID

#5199 Release Candidate for 1.24.1016.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAdminConsentRequestPolicy/MSFT_AADAdminConsentRequestPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADCustomSecurityAttributeDefinition/MSFT_AADCustomSecurityAttributeDefinition.schema.mof
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.1016.1
