Repository microsoft/Microsoft365DSC, pull requests merged in 2024-07, with the labels that each got.

#4834 Migrate Intune ASR resource to new settings catalog cmdlets
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneAccountProtectionLocalAdministratorPasswordSolutionPolicy/MSFT_IntuneAccountProtectionLocalAdministratorPasswordSolutionPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneExploitProtectionPolicyWindows10SettingCatalog/MSFT_IntuneExploitProtectionPolicyWindows10SettingCatalog.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneSettingCatalogASRRulesPolicyWindows10/MSFT_IntuneSettingCatalogASRRulesPolicyWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneSettingCatalogASRRulesPolicyWindows10/MSFT_IntuneSettingCatalogASRRulesPolicyWindows10.schema.mof
  Modules/Microsoft365DSC/Modules/M365DSCDRGUtil.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneAccountProtectionLocalAdministratorPasswordSolutionPolicy.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneSettingCatalogASRRulesPolicyWindows10.Tests.ps1
Labels: Breaking Changes

#4842 Release 1.24.703.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.703.1

#4855 Release 1.24.710.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCTelemetryEngine.psm1
Labels: Release, V1.24.710.1

#4856 Release 1.24.710.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADGroup/MSFT_AADGroup.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOAntiPhishRule/MSFT_EXOAntiPhishRule.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOHostedOutboundSpamFilterRule/MSFT_EXOHostedOutboundSpamFilterRule.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationCustomPolicyWindows10/MSFT_IntuneDeviceConfigurationCustomPolicyWindows10.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPlatformScriptMacOS/MSFT_IntuneDeviceConfigurationPlatformScriptMacOS.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCDRGUtil.psm1
  Modules/Microsoft365DSC/Modules/M365DSCTelemetryEngine.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  docs/docs/resources/intune/IntuneDeviceConfigurationCustomPolicyWindows10.md
Labels: Release, V1.24.710.1

#4860 Release 1.24.710.2
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCTelemetryEngine.psm1
Labels: Release, V1.24.710.2

#4861 Release 1.24.710.2
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCTelemetryEngine.psm1
Labels: Release, V1.24.710.2

#4863 Release 1.24.710.3
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
Labels: Release, V1.24.710.3

#4902 Release 1.24.717.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCTelemetryEngine.psm1
Labels: Release, V1.24.717.1

#4923 Release 1.24.724.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.724.1
