Repository microsoft/Microsoft365DSC, pull requests merged in 2024-04, with the labels that each got.

#4362 Fix Intune device enrollment platform restrictions
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentPlatformRestriction/MSFT_IntuneDeviceEnrollmentPlatformRestriction.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentPlatformRestriction/MSFT_IntuneDeviceEnrollmentPlatformRestriction.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentPlatformRestriction/readme.md
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceEnrollmentPlatformRestriction/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceEnrollmentPlatformRestriction/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceEnrollmentPlatformRestriction/3-Remove.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneDeviceEnrollmentPlatformRestriction.Tests.ps1
Labels: Intune, Breaking Changes

#4512 Release 1.24.403.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleEligibilityScheduleRequest/MSFT_AADRoleEligibilityScheduleRequest.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
Labels: Release, V1.24.403.1

#4573 Release 1.24.417.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleEligibilityScheduleRequest/MSFT_AADRoleEligibilityScheduleRequest.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADRoleSetting/MSFT_AADRoleSetting.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOAuthenticationPolicyAssignment/MSFT_EXOAuthenticationPolicyAssignment.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.417.1

#4602 Release 1.24.424.1
  CHANGELOG.md
  docs/docs/user-guide/get-started/authentication-and-permissions.md
Labels: Release, V1.24.424.1
