Repository microsoft/Microsoft365DSC, pull requests merged in 2024-05, with the labels that each got.

#4674 Release 1.24.515.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.515.1

#4677 Release 1.24.515.2
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOManagementRoleEntry/MSFT_EXOManagementRoleEntry.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOManagementRoleEntry/MSFT_EXOManagementRoleEntry.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsMeetingBroadcastPolicy/MSFT_TeamsMeetingBroadcastPolicy.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCTelemetryEngine.psm1
Labels: Release, V1.24.515.2

#4688 SPOTenantCdnPolicy: Export properties as empty arrays if in the tenant they are empty strings
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantCdnPolicy/MSFT_SPOTenantCdnPolicy.psm1
Labels: SharePoint Online

#4696 Release 1.24.522.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantSettings/MSFT_SPOTenantSettings.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.522.1

#4704 Release 1.24.522.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/MSFT_AADConditionalAccessPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/MSFT_AADConditionalAccessPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPlatformScriptMacOS/MSFT_IntuneDeviceConfigurationPlatformScriptMacOS.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPlatformScriptMacOS/MSFT_IntuneDeviceConfigurationPlatformScriptMacOS.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPlatformScriptMacOS/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPlatformScriptMacOS/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPlatformScriptWindows/MSFT_IntuneDeviceConfigurationPlatformScriptWindows.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPlatformScriptWindows/MSFT_IntuneDeviceConfigurationPlatformScriptWindows.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPlatformScriptWindows/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPlatformScriptWindows/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentPlatformRestriction/MSFT_IntuneDeviceEnrollmentPlatformRestriction.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentStatusPageWindows10/MSFT_IntuneDeviceEnrollmentStatusPageWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceRemediation/MSFT_IntuneDeviceRemediation.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceRemediation/MSFT_IntuneDeviceRemediation.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceRemediation/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceRemediation/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsUpdateForBusinessDriverUpdateProfileWindows10/MSFT_IntuneWindowsUpdateForBusinessDriverUpdateProfileWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsUpdateForBusinessDriverUpdateProfileWindows10/MSFT_IntuneWindowsUpdateForBusinessDriverUpdateProfileWindows10.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsUpdateForBusinessDriverUpdateProfileWindows10/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsUpdateForBusinessDriverUpdateProfileWindows10/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantCdnPolicy/MSFT_SPOTenantCdnPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantSettings/MSFT_SPOTenantSettings.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceConfigurationPlatformScriptMacOS/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceConfigurationPlatformScriptMacOS/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceConfigurationPlatformScriptMacOS/3-Remove.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceConfigurationPlatformScriptWindows/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceConfigurationPlatformScriptWindows/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceConfigurationPlatformScriptWindows/3-Remove.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceRemediation/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceRemediation/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceRemediation/3-Remove.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneWindowsUpdateForBusinessDriverUpdateProfileWindows10/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneWindowsUpdateForBusinessDriverUpdateProfileWindows10/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneWindowsUpdateForBusinessDriverUpdateProfileWindows10/3-Remove.ps1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  Modules/Microsoft365DSC/SchemaDefinition.json
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.INTUNE.Create.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADConditionalAccessPolicy.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneDeviceConfigurationPlatformScriptMacOS.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneDeviceConfigurationPlatformScriptWindows.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneDeviceRemediation.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneWindowsUpdateForBusinessDriverUpdateProfileWindows10.Tests.ps1
  Tests/Unit/Stubs/Microsoft365.psm1
  docs/docs/resources/azure-ad/AADConditionalAccessPolicy.md
  docs/docs/resources/intune/IntuneDeviceConfigurationPlatformScriptMacOS.md
  docs/docs/resources/intune/IntuneDeviceConfigurationPlatformScriptWindows.md
  docs/docs/resources/intune/IntuneDeviceRemediation.md
  docs/docs/resources/intune/IntuneWindowsUpdateForBusinessDriverUpdateProfileWindows10.md
Labels: Release, V1.24.522.1

#4646 O365AdminAuditLogConfig: Fix logging of exception
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_O365AdminAuditLogConfig/MSFT_O365AdminAuditLogConfig.psm1
Labels: Pending Information

#4718 Release 1.24.529.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.529.1
