Repository microsoft/Microsoft365DSC, pull requests merged in 2024-09, with the labels that each got.

#5018 FabricAdminTenantSettings - Initial Release
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_FabricAdminTenantSettings/MSFT_FabricAdminTenantSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_FabricAdminTenantSettings/MSFT_FabricAdminTenantSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_FabricAdminTenantSettings/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_FabricAdminTenantSettings/settings.json
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Examples/Resources/FabricAdminTenantSettings/4-MonitorOnly.ps1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCReverse.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  Modules/Microsoft365DSC/Modules/WorkloadHelpers/M365DSCFabricHelper.psm1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.FabricAdminTenantSettings.Tests.ps1
  Tests/Unit/Stubs/Generic.psm1
Labels: Fabric

#5019 Release 1.24.904.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.904.1

#5020 Release 1.24.904.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOOwaMailboxPolicy/MSFT_EXOOwaMailboxPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOOwaMailboxPolicy/MSFT_EXOOwaMailboxPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOSweepRule/MSFT_EXOSweepRule.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOSweepRule/MSFT_EXOSweepRule.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOSweepRule/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOSweepRule/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_FabricAdminTenantSettings/MSFT_FabricAdminTenantSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_FabricAdminTenantSettings/MSFT_FabricAdminTenantSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_FabricAdminTenantSettings/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_FabricAdminTenantSettings/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceControlPolicyWindows10/MSFT_IntuneDeviceControlPolicyWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceControlPolicyWindows10/MSFT_IntuneDeviceControlPolicyWindows10.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceControlPolicyWindows10/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceControlPolicyWindows10/settings.json
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Examples/Resources/EXOSweepRule/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXOSweepRule/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXOSweepRule/3-Remove.ps1
  Modules/Microsoft365DSC/Examples/Resources/FabricAdminTenantSettings/4-MonitorOnly.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceControlPolicyWindows10/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceControlPolicyWindows10/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/IntuneDeviceControlPolicyWindows10/3-Remove.ps1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCDRGUtil.psm1
  Modules/Microsoft365DSC/Modules/M365DSCReverse.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  Modules/Microsoft365DSC/Modules/WorkloadHelpers/M365DSCFabricHelper.psm1
  Modules/Microsoft365DSC/SchemaDefinition.json
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.EXO.Create.Tests.ps1
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.EXO.Remove.Tests.ps1
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.EXO.Update.Tests.ps1
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.INTUNE.Create.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOSweepRule.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.FabricAdminTenantSettings.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneDeviceControlPolicyWindows10.Tests.ps1
  Tests/Unit/Stubs/Generic.psm1
  Tests/Unit/Stubs/Microsoft365.psm1
  dev-package/Modules/Microsoft365DSC/DSCResources/MSFT_ResourceName/MSFT_ResourceName.psm1
  dev-package/Modules/Microsoft365DSC/DSCResources/MSFT_ResourceName/MSFT_ResourceName.schema.mof
  dev-package/Modules/Microsoft365DSC/DSCResources/MSFT_ResourceName/readme.md
  dev-package/Modules/Microsoft365DSC/DSCResources/MSFT_ResourceName/settings.json
  dev-package/Modules/Microsoft365DSC/Examples/Resources/ResourceName/1-Create.ps1
  dev-package/Modules/Microsoft365DSC/Examples/Resources/ResourceName/2-Update.ps1
  dev-package/Modules/Microsoft365DSC/Examples/Resources/ResourceName/3-Remove.ps1
  dev-package/Tests/Unit/Microsoft365DSC/Microsoft365DSC.ResourceName.Tests.ps1
  docs/docs/resources/exchange/EXOOwaMailboxPolicy.md
  docs/docs/resources/exchange/EXOSweepRule.md
  docs/docs/resources/exchange/FabricAdminTenantSettings.md
  docs/docs/resources/intune/IntuneDeviceControlPolicyWindows10.md
  docs/docs/user-guide/cmdlets/Export-M365DSCConfiguration.md
Labels: Release, V1.24.904.1

#4966 New DSC-resource: AAD Password Rule Settings
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADPasswordRuleSettings/MSFT_AADPasswordRuleSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADPasswordRuleSettings/MSFT_AADPasswordRuleSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADPasswordRuleSettings/Readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADPasswordRuleSettings/settings.json
  Modules/Microsoft365DSC/Examples/Resources/AADPasswordRuleSettings/1-Update.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADPasswordRuleSettings.Tests.ps1
Labels: Pending Information, Entra ID
