Repository microsoft/Microsoft365DSC, pull requests merged in 2024-12, with the labels that each got.

#5512 Release 1.24.1204.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.1204.1

#5538 Release 1.24.1211.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.1211.1

#5554 Fixing Fabric API calls
  CHANGELOG.md
  Modules/Microsoft365DSC/Modules/WorkloadHelpers/M365DSCFabricHelper.psm1
Labels: Fabric

#5584 Release 1.24.1218.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOTransportRule/MSFT_EXOTransportRule.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.1218.1
