Repository microsoft/Microsoft365DSC, pull requests merged in 2024-02, with the labels that each got.

#4284 Release 1.24.131.2
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsMeetingPolicy/MSFT_TeamsMeetingPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUpdateManagementPolicy/MSFT_TeamsUpdateManagementPolicy.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.131.2

#4285 Release 1.24.131.2
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsMeetingPolicy/MSFT_TeamsMeetingPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUpdateManagementPolicy/MSFT_TeamsUpdateManagementPolicy.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.131.2

#4300 Release 1.24.207.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.207.1

#4301 Release 1.24.207.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXORecipientPermission/MSFT_EXORecipientPermission.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXORecipientPermission/MSFT_EXORecipientPermission.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXORecipientPermission/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXORecipientPermission/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyAndroidOpenSourceProject/MSFT_IntuneDeviceConfigurationPolicyAndroidOpenSourceProject.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentPlatformRestriction/MSFT_IntuneDeviceEnrollmentPlatformRestriction.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentPlatformRestriction/MSFT_IntuneDeviceEnrollmentPlatformRestriction.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneExploitProtectionPolicyWindows10SettingCatalog/MSFT_IntuneExploitProtectionPolicyWindows10SettingCatalog.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneRoleAssignment/MSFT_IntuneRoleAssignment.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneRoleDefinition/MSFT_IntuneRoleDefinition.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneSettingCatalogASRRulesPolicyWindows10/MSFT_IntuneSettingCatalogASRRulesPolicyWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWiFiConfigurationPolicyAndroidDeviceAdministrator/MSFT_IntuneWiFiConfigurationPolicyAndroidDeviceAdministrator.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseDeviceOwner/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseDeviceOwner.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseWorkProfile/MSFT_IntuneWifiConfigurationPolicyAndroidEnterpriseWorkProfile.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidForWork/MSFT_IntuneWifiConfigurationPolicyAndroidForWork.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyAndroidOpenSourceProject/MSFT_IntuneWifiConfigurationPolicyAndroidOpenSourceProject.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyIOS/MSFT_IntuneWifiConfigurationPolicyIOS.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyMacOS/MSFT_IntuneWifiConfigurationPolicyMacOS.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWifiConfigurationPolicyWindows10/MSFT_IntuneWifiConfigurationPolicyWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCDLPComplianceRule/MSFT_SCDLPComplianceRule.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsCallParkPolicy/MSFT_TeamsCallParkPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsCallQueue/MSFT_TeamsCallQueue.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsFilesPolicy/MSFT_TeamsFilesPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsMeetingPolicy/MSFT_TeamsMeetingPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUserCallingSettings/MSFT_TeamsUserCallingSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUserCallingSettings/MSFT_TeamsUserCallingSettings.schema.mof
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Examples/Resources/EXOGroupSettings/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXOMailboxAutoReplyConfiguration/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXOMailboxCalendarFolder/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXOMailboxPermission/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXORecipientPermission/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXORecipientPermission/3-Remove.ps1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCDRGUtil.psm1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXODataClassification.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXORecipientPermission.Tests.ps1
  Tests/Unit/Stubs/Microsoft365.psm1
  docs/docs/user-guide/get-started/powershell7-support.md
Labels: Release, V1.24.207.1

#4310 Release 1.24.207.2
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.207.2

#4311 Release 1.24.207.2
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCTelemetryEngine.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
Labels: Release, V1.24.207.2

#4330 Release 1.24.214.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.214.1

#4332 Release 1.24.214.2
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
Labels: Release, V1.24.214.2

#4348 Release 1.24.214.3 - Fixes Issues with MS Graph PowerShell SDK
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicy/MSFT_AADAuthenticationMethodPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyAuthenticator/MSFT_AADAuthenticationMethodPolicyAuthenticator.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyEmail/MSFT_AADAuthenticationMethodPolicyEmail.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyFido2/MSFT_AADAuthenticationMethodPolicyFido2.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicySms/MSFT_AADAuthenticationMethodPolicySms.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicySoftware/MSFT_AADAuthenticationMethodPolicySoftware.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyTemporary/MSFT_AADAuthenticationMethodPolicyTemporary.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyVoice/MSFT_AADAuthenticationMethodPolicyVoice.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyX509/MSFT_AADAuthenticationMethodPolicyX509.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneAppConfigurationPolicy/MSFT_IntuneAppConfigurationPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentStatusPageWindows10/MSFT_IntuneDeviceEnrollmentStatusPageWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsAutopilotDeploymentProfileAzureADJoined/MSFT_IntuneWindowsAutopilotDeploymentProfileAzureADJoined.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCDLPComplianceRule/MSFT_SCDLPComplianceRule.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCTelemetryEngine.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
Labels: Release, V1.24.214.3

#4349 Release 1.24.214.3
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicy/MSFT_AADAuthenticationMethodPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyAuthenticator/MSFT_AADAuthenticationMethodPolicyAuthenticator.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyEmail/MSFT_AADAuthenticationMethodPolicyEmail.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyFido2/MSFT_AADAuthenticationMethodPolicyFido2.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicySms/MSFT_AADAuthenticationMethodPolicySms.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicySoftware/MSFT_AADAuthenticationMethodPolicySoftware.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyTemporary/MSFT_AADAuthenticationMethodPolicyTemporary.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyVoice/MSFT_AADAuthenticationMethodPolicyVoice.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyX509/MSFT_AADAuthenticationMethodPolicyX509.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneAppConfigurationPolicy/MSFT_IntuneAppConfigurationPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceEnrollmentStatusPageWindows10/MSFT_IntuneDeviceEnrollmentStatusPageWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneWindowsAutopilotDeploymentProfileAzureADJoined/MSFT_IntuneWindowsAutopilotDeploymentProfileAzureADJoined.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCDLPComplianceRule/MSFT_SCDLPComplianceRule.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCTelemetryEngine.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
Labels: Release, V1.24.214.3

#4359 Release 1.24.221.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/MSFT_AADConditionalAccessPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/MSFT_AADConditionalAccessPolicy.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOActiveSyncDeviceAccessRule/MSFT_EXOActiveSyncDeviceAccessRule.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOAuthenticationPolicyAssignment/MSFT_EXOAuthenticationPolicyAssignment.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOAvailabilityAddressSpace/MSFT_EXOAvailabilityAddressSpace.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOAvailabilityConfig/MSFT_EXOAvailabilityConfig.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOCASMailboxPlan/MSFT_EXOCASMailboxPlan.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOCASMailboxPlan/MSFT_EXOCASMailboxPlan.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXODataClassification/MSFT_EXODataClassification.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOGroupSettings/MSFT_EXOGroupSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOGroupSettings/MSFT_EXOGroupSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailboxAutoReplyConfiguration/MSFT_EXOMailboxAutoReplyConfiguration.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailboxAutoReplyConfiguration/MSFT_EXOMailboxAutoReplyConfiguration.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailboxPlan/MSFT_EXOMailboxPlan.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailboxPlan/MSFT_EXOMailboxPlan.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailboxSettings/MSFT_EXOMailboxSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMessageClassification/MSFT_EXOMessageClassification.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOPlace/MSFT_EXOPlace.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOPlace/MSFT_EXOPlace.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXORecipientPermission/MSFT_EXORecipientPermission.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOSharedMailbox/MSFT_EXOSharedMailbox.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOSharedMailbox/MSFT_EXOSharedMailbox.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOTransportRule/MSFT_EXOTransportRule.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationAdministrativeTemplatePolicyWindows10/MSFT_IntuneDeviceConfigurationAdministrativeTemplatePolicyWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCLabelPolicy/MSFT_SCLabelPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.psm1
  Modules/Microsoft365DSC/Examples/Resources/AADApplication/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/AADApplication/2-Update.ps1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCAgent.psm1
  Modules/Microsoft365DSC/Modules/M365DSCReport.psm1
  Modules/Microsoft365DSC/Modules/M365DSCTelemetryEngine.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.AAD.Create.Tests.ps1
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.AAD.Update.Tests.ps1
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.EXO.Update.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADApplication.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOAuthenticationPolicyAssignment.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOAvailabilityAddressSpace.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOAvailabilityConfig.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOGroupSettings.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOTransportRule.Tests.ps1
  docs/docs/resources/azure-ad/AADApplication.md
  docs/docs/resources/azure-ad/AADConditionalAccessPolicy.md
  docs/docs/resources/exchange/EXOActiveSyncDeviceAccessRule.md
  docs/docs/resources/exchange/EXOCASMailboxPlan.md
  docs/docs/resources/exchange/EXOGroupSettings.md
  docs/docs/resources/exchange/EXOMailboxAutoReplyConfiguration.md
  docs/docs/resources/exchange/EXOMailboxPlan.md
  docs/docs/resources/exchange/EXOPlace.md
  docs/docs/resources/exchange/EXOSharedMailbox.md
Labels: Release, V1.24.221.1

#4387 Release 1.24.228.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.228.1
