Repository microsoft/Microsoft365DSC, pull requests merged in 2024-11, with the labels that each got.

#5317 M365DSCRuleEvaluation - Renaming Key Property
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_M365DSCRuleEvaluation/MSFT_M365DSCRuleEvaluation.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_M365DSCRuleEvaluation/MSFT_M365DSCRuleEvaluation.schema.mof
  Modules/Microsoft365DSC/Examples/Resources/M365DSCRuleEvaluation/1-Evaluate a rule.ps1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.M365DSCRuleEvaluation.Tests.ps1
Labels: Core Engine, Breaking Changes

#5346 Release 1.24.1106.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.1106.1

#5370 Release 1.24.1106.3
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.1106.3

#5435 Release 1.24.1120.1
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.1120.1

#5477 Release 1.24.1127.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.24.1127.1
