Repository microsoft/Microsoft365DSC, pull requests merged in 2025-08, with the labels that each got.

#6390 Fix property name
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneMobileAppsWin32AppWindows10/MSFT_IntuneMobileAppsWin32AppWindows10.schema.mof
Labels: Intune

#6417 Release 1.25.806.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOFocusedInbox/MSFT_EXOFocusedInbox.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailboxAuditBypassAssociation/MSFT_EXOMailboxAuditBypassAssociation.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailboxCalendarConfiguration/MSFT_EXOMailboxCalendarConfiguration.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsMeetingBroadcastConfiguration/MSFT_TeamsMeetingBroadcastConfiguration.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsMeetingBroadcastConfiguration/settings.json
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.25.806.1

#6463 Release 1.25.827.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOIRMConfiguration/MSFT_EXOIRMConfiguration.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOIRMConfiguration.Tests.ps1
Labels: Release, V1.25.827.1
