Repository microsoft/Microsoft365DSC, pull requests merged in 2025-03, with the labels that each got.

#5870 AADAuthenticationMethodPolicyQRCodeImage
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyQRCodeImage/MSFT_AADAuthenticationMethodPolicyQRCodeImage.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyQRCodeImage/MSFT_AADAuthenticationMethodPolicyQRCodeImage.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyQRCodeImage/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADAuthenticationMethodPolicyQRCodeImage/settings.json
  Modules/Microsoft365DSC/Examples/Resources/AADAuthenticationMethodPolicyQRCodeImage/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/AADAuthenticationMethodPolicyQRCodeImage/3-Remove.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADAuthenticationMethodPolicyQRCodeImage.Tests.ps1
Labels: Enhancement, Entra ID

#5871 PPPowerAppsEnvironment - Fixes for Legacy Types
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_PPPowerAppsEnvironment/MSFT_PPPowerAppsEnvironment.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_PPPowerAppsEnvironment/MSFT_PPPowerAppsEnvironment.schema.mof
Labels: Power Platform

#5881 Release 1.25.305.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.25.305.1

#5890 SCDLPCompliancePolicy - Fix Get
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_SCDLPCompliancePolicy/MSFT_SCDLPCompliancePolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCInsiderRiskEntityList/MSFT_SCInsiderRiskEntityList.psm1
Labels: Bug, Security & Compliance Center

#5903 IntuneDeviceManagementEnrollmentAndroidGooglePlay
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceManagementEnrollmentAndroidGooglePlay/MSFT_IntuneDeviceManagementEnrollmentAndroidGooglePlay.psm1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.IntuneDeviceManagementEnrollmentAndroidGooglePlay.Tests.ps1
Labels: Intune

#5911 Release 1.25.312.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.25.312.1

#5926 TeamsApplicationInstance - New Resource
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsApplicationInstance/MSFT_TeamsApplicationInstance.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsApplicationInstance/MSFT_TeamsApplicationInstance.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsApplicationInstance/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsApplicationInstance/settings.json
  Modules/Microsoft365DSC/Examples/Resources/TeamsApplicationInstance/1-Create.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.TeamsApplicationInstance.Tests.ps1
  Tests/Unit/Stubs/Microsoft365.psm1
Labels: Enhancement, Teams

#5934 Release 1.25.319.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOManagementRoleAssignment/MSFT_EXOManagementRoleAssignment.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADServicePrincipal.Tests.ps1
Labels: Release, V1.25.319.1

#5938 Release 1.25.319.1
  .github/workflows/ResourceIntegration.yml
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOManagementRoleAssignment/MSFT_EXOManagementRoleAssignment.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceOwner/MSFT_IntuneDeviceConfigurationPolicyAndroidDeviceOwner.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCPolicyConfig/MSFT_SCPolicyConfig.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SHSpaceGroup/MSFT_SHSpaceGroup.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SHSpaceGroup/MSFT_SHSpaceGroup.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_SHSpaceGroup/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_SHSpaceGroup/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_SHSpaceUser/MSFT_SHSpaceUser.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SHSpaceUser/MSFT_SHSpaceUser.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_SHSpaceUser/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_SHSpaceUser/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsApplicationInstance/MSFT_TeamsApplicationInstance.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsApplicationInstance/MSFT_TeamsApplicationInstance.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsApplicationInstance/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsApplicationInstance/settings.json
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Examples/Resources/SHSpaceGroup/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/SHSpaceGroup/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/SHSpaceGroup/3-Remove.ps1
  Modules/Microsoft365DSC/Examples/Resources/SHSpaceUser/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/SHSpaceUser/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/SHSpaceUser/3-Remove.ps1
  Modules/Microsoft365DSC/Examples/Resources/TeamsApplicationInstance/1-Create.ps1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCDRGUtil.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  Modules/Microsoft365DSC/Modules/WorkloadHelpers/M365DSCServicesHubHelper.psm1
  Modules/Microsoft365DSC/SchemaDefinition.json
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.AAD.Create.Tests.ps1
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.AAD.Remove.Tests.ps1
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.AAD.Update.Tests.ps1
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.EXO.Create.Tests.ps1
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.EXO.Remove.Tests.ps1
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.EXO.Update.Tests.ps1
  Tests/Integration/Microsoft365DSC/M365DSCIntegration.INTUNE.Create.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADServicePrincipal.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.SHSpaceGroup.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.SHSpaceUser.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.TeamsApplicationInstance.Tests.ps1
  Tests/Unit/Stubs/Microsoft365.psm1
  docs/docs/resources/security-compliance/SCPolicyConfig.md
  docs/docs/resources/sentinel/SHSpaceGroup.md
  docs/docs/resources/sentinel/SHSpaceUser.md
  docs/docs/resources/teams/TeamsApplicationInstance.md
Labels: Release, V1.25.319.1

#5952 Release 1.25.326.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.25.326.1

#5955 Release 1.25.326.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOGroupSettings/MSFT_EXOGroupSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOGroupSettings/MSFT_EXOGroupSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneAppProtectionPolicyiOS/MSFT_IntuneAppProtectionPolicyiOS.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_M365DSCRuleEvaluation/MSFT_M365DSCRuleEvaluation.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCDeviceConfigurationPolicy/MSFT_SCDeviceConfigurationPolicy.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/SchemaDefinition.json
  docs/docs/resources/azure-ad/AADApplication.md
  docs/docs/resources/exchange/EXOGroupSettings.md
Labels: Release, V1.25.326.1

#5773 BREAKING CHANGE: Remove EXOMailTips resource
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailTips/MSFT_EXOMailTips.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailTips/MSFT_EXOMailTips.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailTips/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailTips/settings.json
  Modules/Microsoft365DSC/Examples/Resources/EXOMailTips/2-Update.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOMailTips.Tests.ps1
Labels: Exchange Online, Breaking Changes

#5789 BREAKING CHANGE: Remove deprecated parameter from resource
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneSecurityBaselineMicrosoftEdge/MSFT_IntuneSecurityBaselineMicrosoftEdge.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneSecurityBaselineMicrosoftEdge/MSFT_IntuneSecurityBaselineMicrosoftEdge.schema.mof
Labels: Intune, Breaking Changes

#5790 BREAKING CHANGE: Remove value from Action parameter
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneAccountProtectionLocalUserGroupMembershipPolicy/MSFT_IntuneAccountProtectionLocalUserGroupMembershipPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneAccountProtectionLocalUserGroupMembershipPolicy/MSFT_IntuneAccountProtectionLocalUserGroupMembershipPolicy.schema.mof
Labels: Intune, Breaking Changes

#5917 Remove Identity parameter from EXOArcConfig
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOArcConfig/MSFT_EXOArcConfig.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOArcConfig/MSFT_EXOArcConfig.schema.mof
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOArcConfig.Tests.ps1
Labels: Exchange Online, Breaking Changes

#5897 Fix export of SPOTheme palette property
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTheme/MSFT_SPOTheme.psm1
Labels: Pending Information, SharePoint Online

#5748 Add AuditEnabled to EXOSharedMailbox
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOSharedMailbox/MSFT_EXOSharedMailbox.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOSharedMailbox/MSFT_EXOSharedMailbox.schema.mof
Labels: Pending Information, Exchange Online

#5747 Add AuditEnabled property to EXOMailboxSettings
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailboxSettings/MSFT_EXOMailboxSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOMailboxSettings/MSFT_EXOMailboxSettings.schema.mof
Labels: Pending Information, Exchange Online

#5966 BREAKING CHANGE: Update parameter value possibilities in password rule setting
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADPasswordRuleSettings/MSFT_AADPasswordRuleSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADPasswordRuleSettings/MSFT_AADPasswordRuleSettings.schema.mof
Labels: Entra ID, Breaking Changes

#5867 Proposal: Add PowerShell 5 to 7 compatibility layer
  CHANGELOG.md
  Modules/Microsoft365DSC/Modules/M365DSCTelemetryEngine.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
Labels: Core Engine, Proposal
