Repository microsoft/Microsoft365DSC, pull requests merged in 2025-02, with the labels that each got.

#5726 Commerce self service purchase
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_CommerceSelfServicePurchase/MSFT_CommerceSelfServicePurchase.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_CommerceSelfServicePurchase/MSFT_CommerceSelfServicePurchase.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_CommerceSelfServicePurchase/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_CommerceSelfServicePurchase/settings.json
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Examples/Resources/CommerceSelfServicePurchase/2-Update.ps1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
  Modules/Microsoft365DSC/Modules/WorkloadHelpers/M365DSCLicensingHelper.psm1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.CommerceSelfServicePurchase.Tests.ps1
Labels: Commerce

#5732 Release 1.25.205.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConnectorGroupApplicationProxy/MSFT_AADConnectorGroupApplicationProxy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SCPolicyConfig/MSFT_SCPolicyConfig.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.25.205.1

#5744 EXORetentionPolicyTag - Initial Release
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXORetentionPolicyTag/MSFT_EXORetentionPolicyTag.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXORetentionPolicyTag/MSFT_EXORetentionPolicyTag.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_EXORetentionPolicyTag/readme.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXORetentionPolicyTag/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_PPTenantSettings/MSFT_PPTenantSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_PPTenantSettings/MSFT_PPTenantSettings.schema.mof
  Modules/Microsoft365DSC/Examples/Resources/EXORetentionPolicyTag/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXORetentionPolicyTag/2-Update.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXORetentionPolicyTag/3-Remove.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXORetentionPolicyTag.Tests.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.PPTenantSettings.Tests.ps1
  Tests/Unit/Stubs/Microsoft365.psm1
Labels: Exchange Online

#5754 AADApplication - Allow for Nullable AuthenticationBehaviors
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADApplication/MSFT_AADApplication.schema.mof
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.AADApplication.Tests.ps1
Labels: Entra ID

#5758 Release 1.25.212.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADIdentityAPIConnector/MSFT_AADIdentityAPIConnector.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.25.212.1

#5778 Release 1.25.212.2
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_PPAdminDLPPolicy/MSFT_PPAdminDLPPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_PPDLPPolicyConnectorConfigurations/MSFT_PPDLPPolicyConnectorConfigurations.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_PPPowerAppPolicyUrlPatterns/MSFT_PPPowerAppPolicyUrlPatterns.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_PPTenantIsolationSettings/MSFT_PPTenantIsolationSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_PPTenantSettings/MSFT_PPTenantSettings.psm1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  README.md
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.PPPowerAppPolicyUrlPatterns.Tests.ps1
Labels: Release, V1.25.212.2

#5753 To Fix issue 5752
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsAppSetupPolicy/MSFT_TeamsAppSetupPolicy.psm1
Labels: Pending Information, Teams

#5780 ADOSecurityPolicy - Fix Default Value Parsing
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_ADOSecurityPolicy/MSFT_ADOSecurityPolicy.psm1
  Modules/Microsoft365DSC/Modules/M365DSCUtil.psm1
Labels: DevOps

#5811 Release 1.25.219.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.25.219.1

#5816 Release 1.25.219.2
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_PPTenantSettings/MSFT_PPTenantSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.25.219.2

#5817 Release 1.25.219.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_PPTenantSettings/MSFT_PPTenantSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_SCSensitivityLabel/MSFT_SCSensitivityLabel.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
  docs/docs/resources/power-platform/PPTenantSettings.md
Labels: Release, V1.25.219.2

#5840 Release 1.25.219.3
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/MSFT_AADConditionalAccessPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_M365DSCRuleEvaluation/MSFT_M365DSCRuleEvaluation.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.25.219.3

#5749 Add additional properties to SPOTenantSettings
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantSettings/MSFT_SPOTenantSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantSettings/MSFT_SPOTenantSettings.schema.mof
Labels: SharePoint Online

#5845 Release 1.25.226.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/MSFT_AADConditionalAccessPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_O365OrgSettings/MSFT_O365OrgSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_O365OrgSettings/MSFT_O365OrgSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_O365OrgSettings/settings.json
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
Labels: Release, V1.25.226.1

#5846 Release 1.25.226.1
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADConditionalAccessPolicy/MSFT_AADConditionalAccessPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_AADPasswordRuleSettings/MSFT_AADPasswordRuleSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCompliancePolicyWindows10/MSFT_IntuneDeviceCompliancePolicyWindows10.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneDeviceCompliancePolicyWindows10/MSFT_IntuneDeviceCompliancePolicyWindows10.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_O365OrgSettings/MSFT_O365OrgSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_O365OrgSettings/MSFT_O365OrgSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_O365OrgSettings/settings.json
  Modules/Microsoft365DSC/DSCResources/MSFT_PPTenantSettings/MSFT_PPTenantSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOSiteScript/MSFT_SPOSiteScript.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantSettings/MSFT_SPOTenantSettings.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_SPOTenantSettings/MSFT_SPOTenantSettings.schema.mof
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsChannel/MSFT_TeamsChannel.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsTeam/MSFT_TeamsTeam.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_TeamsUser/MSFT_TeamsUser.psm1
  Modules/Microsoft365DSC/Dependencies/Manifest.psd1
  Modules/Microsoft365DSC/SchemaDefinition.json
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.SPOSiteScript.Tests.ps1
  Tests/Unit/Stubs/Microsoft365.psm1
  docs/docs/resources/azure-ad/AADPasswordRuleSettings.md
  docs/docs/resources/intune/IntuneDeviceCompliancePolicyWindows10.md
  docs/docs/resources/office365/O365OrgSettings.md
  docs/docs/resources/power-platform/PPTenantSettings.md
  docs/docs/resources/sharepoint/SPOTenantSettings.md
Labels: Release, V1.25.226.1
