Repository microsoft/Microsoft365DSC, pull requests merged in 2025-09, with the labels that each got.

#6406 Fix get and set error messages in AAD Service Principal
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_AADServicePrincipal/MSFT_AADServicePrincipal.psm1
Labels: Pending Information

#6467 Fix IntuneMobileAppsWindowsOfficeSuiteApp policies,Problem with XML c…
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_IntuneMobileAppsWindowsOfficeSuiteApp/MSFT_IntuneMobileAppsWindowsOfficeSuiteApp.psm1
Labels: Pending Information, Intune

#6475 Release 1.25.903.1
  CHANGELOG.md
  Modules/Microsoft365DSC/Microsoft365DSC.psd1
Labels: Release, V1.25.903.1

#6036 Breaking Change - Remove deprecated parameters from EXOHostedContentFilterPolicy
  CHANGELOG.md
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOHostedContentFilterPolicy/MSFT_EXOHostedContentFilterPolicy.psm1
  Modules/Microsoft365DSC/DSCResources/MSFT_EXOHostedContentFilterPolicy/MSFT_EXOHostedContentFilterPolicy.schema.mof
  Modules/Microsoft365DSC/Examples/Resources/EXOHostedContentFilterPolicy/1-Create.ps1
  Modules/Microsoft365DSC/Examples/Resources/EXOHostedContentFilterPolicy/2-Update.ps1
  Tests/Unit/Microsoft365DSC/Microsoft365DSC.EXOHostedContentFilterPolicy.Tests.ps1
Labels: Exchange Online, Breaking Changes
